<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LocationValue</name>
   <tag></tag>
   <elementGuidId>27b82638-b421-4230-9d1d-05a0f4be7b52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='select2-drop']//span[text()=&quot;Nairobi&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='select2-drop']//span[text()=&quot;Nairobi&quot;]</value>
   </webElementProperties>
</WebElementEntity>
