<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TourType</name>
   <tag></tag>
   <elementGuidId>99c6d439-bccf-4acb-8d6d-a1835cfc7f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='s2id_autogen11']//span[text()='Select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='s2id_autogen11']//span[text()='Select']</value>
   </webElementProperties>
</WebElementEntity>
