<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button-Edit</name>
   <tag></tag>
   <elementGuidId>49b2bfc8-4a27-4c3c-94c8-4732d48cc023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='content']/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[1]/td[7]/span/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='content']/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[1]/td[7]/span/a[2]/i</value>
   </webElementProperties>
</WebElementEntity>
